name: CI/CD for SBC
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker
        run: docker build -t sbc-ims .
      - name: Test
        run: echo "Build passed!"
